services:
  server:
    image: server
    build:
      context: ./server/
    ports:
      - "3000:3000"
  
  client:
    image: client
    build:
      context: ./client/
    ports:
      - "80:5173"
